// Allow warnings generated by PyO3 macros
#![allow(non_local_definitions)]

use pyo3::prelude::*;

// Module declarations
mod error;
mod auth;
mod request;
mod response;
mod streaming;
mod config;
mod utils;
mod core;
mod client;
mod async_client;
mod global;
mod runtime;
mod models;
mod hooks;
mod ssl_config;
mod transport;
mod proxy_config;

// Re-export main types and functions
pub use error::*;
pub use auth::*;
pub use request::HttpRequest;
pub use response::HttpResponse;
pub use streaming::{StreamingHttpResponse, StreamingBytesIterator, StreamingTextIterator, StreamingLinesIterator, StreamingClient};
pub use config::ClientConfig;
pub use client::HttpClient;
pub use async_client::AsyncHttpClient;
// Re-export global functions (request function is available via Python module, not Rust re-export)
pub use global::{get, post, put, patch, delete, head, options, stream};
pub use models::{HttpHeaders, HttpQueryParams, HttpCookies, HttpUrl, HttpTimeout, HttpLimits, HttpBasicAuth, HttpDigestAuth, HttpNetRCAuth};

// Python module definition
#[pymodule]
fn _core(py: Python, m: &PyModule) -> PyResult<()> {
    // Add classes
    m.add_class::<HttpRequest>()?;
    m.add_class::<HttpResponse>()?;
    m.add_class::<StreamingHttpResponse>()?;
    m.add_class::<StreamingClient>()?;
    m.add_class::<StreamingBytesIterator>()?;
    m.add_class::<StreamingTextIterator>()?;
    m.add_class::<StreamingLinesIterator>()?;
    m.add_class::<HttpClient>()?;
    m.add_class::<AsyncHttpClient>()?;
    
    // Add data model classes
    m.add_class::<HttpHeaders>()?;
    m.add_class::<HttpQueryParams>()?;
    m.add_class::<HttpCookies>()?;
    m.add_class::<HttpUrl>()?;
    m.add_class::<HttpTimeout>()?;
    m.add_class::<HttpLimits>()?;
    m.add_class::<HttpBasicAuth>()?;
    m.add_class::<HttpDigestAuth>()?;
    m.add_class::<HttpNetRCAuth>()?;
    
    // Add transport classes  
    m.add_class::<transport::FasterhttpTransport>()?;
    m.add_class::<transport::MockTransport>()?;
    m.add_class::<transport::HTTPSRedirectTransport>()?;
    
    // Add global functions
    m.add_function(wrap_pyfunction!(global::get, m)?)?;
    m.add_function(wrap_pyfunction!(global::post, m)?)?;
    m.add_function(wrap_pyfunction!(global::put, m)?)?;
    m.add_function(wrap_pyfunction!(global::patch, m)?)?;
    m.add_function(wrap_pyfunction!(global::delete, m)?)?;
    m.add_function(wrap_pyfunction!(global::head, m)?)?;
    m.add_function(wrap_pyfunction!(global::options, m)?)?;
    m.add_function(wrap_pyfunction!(global::request, m)?)?;
    m.add_function(wrap_pyfunction!(global::stream, m)?)?;
    
    // Add exception types - complete hierarchy
    m.add("HTTPError", py.get_type::<HTTPError>())?;
    
    // Connection exceptions
    m.add("ConnectError", py.get_type::<ConnectError>())?;
    m.add("ConnectTimeout", py.get_type::<ConnectTimeout>())?;
    
    // Timeout exceptions
    m.add("TimeoutException", py.get_type::<TimeoutException>())?;
    m.add("ReadTimeout", py.get_type::<ReadTimeout>())?;
    m.add("WriteTimeout", py.get_type::<WriteTimeout>())?;
    m.add("PoolTimeout", py.get_type::<PoolTimeout>())?;
    
    // Request/Response exceptions
    m.add("RequestError", py.get_type::<RequestError>())?;
    m.add("ResponseError", py.get_type::<ResponseError>())?;
    
    // HTTP Status exceptions
    m.add("HTTPStatusError", py.get_type::<HTTPStatusError>())?;
    m.add("ClientError", py.get_type::<ClientError>())?;
    m.add("ServerError", py.get_type::<ServerError>())?;
    
    // Stream exceptions
    m.add("StreamError", py.get_type::<StreamError>())?;
    m.add("StreamConsumed", py.get_type::<StreamConsumed>())?;
    m.add("StreamClosed", py.get_type::<StreamClosed>())?;
    
    // Protocol exceptions
    m.add("ProtocolError", py.get_type::<ProtocolError>())?;
    m.add("DecodingError", py.get_type::<DecodingError>())?;
    m.add("TooManyRedirects", py.get_type::<TooManyRedirects>())?;
    
    // Transport exceptions
    m.add("TransportError", py.get_type::<TransportError>())?;
    m.add("ProxyError", py.get_type::<ProxyError>())?;
    m.add("SSLError", py.get_type::<SSLError>())?;
    m.add("CertificateError", py.get_type::<CertificateError>())?;
    
    // Network exceptions
    m.add("NetworkError", py.get_type::<NetworkError>())?;
    m.add("DNSError", py.get_type::<DNSError>())?;
    
    Ok(())
} 