// Allow warnings generated by PyO3 macros
#![allow(non_local_definitions)]

use pyo3::prelude::*;

// Module declarations
mod error;
mod auth;
mod request;
mod response;
mod streaming;
mod config;
mod utils;
mod core;
mod client;
mod async_client;
mod global;
mod runtime;
mod models;

// Re-export main types and functions
pub use error::*;
pub use auth::*;
pub use request::HttpRequest;
pub use response::HttpResponse;
pub use streaming::{StreamingHttpResponse, StreamingBytesIterator, StreamingTextIterator, StreamingLinesIterator};
pub use config::ClientConfig;
pub use client::HttpClient;
pub use async_client::AsyncHttpClient;
pub use global::*;
pub use models::{HttpHeaders, HttpQueryParams, HttpCookies, HttpUrl, HttpTimeout, HttpLimits, HttpBasicAuth, HttpDigestAuth, HttpNetRCAuth};

// Python module definition
#[pymodule]
fn _core(py: Python, m: &PyModule) -> PyResult<()> {
    // Add classes
    m.add_class::<HttpRequest>()?;
    m.add_class::<HttpResponse>()?;
    m.add_class::<StreamingHttpResponse>()?;
    m.add_class::<StreamingBytesIterator>()?;
    m.add_class::<StreamingTextIterator>()?;
    m.add_class::<StreamingLinesIterator>()?;
    m.add_class::<HttpClient>()?;
    m.add_class::<AsyncHttpClient>()?;
    
    // Add data model classes
    m.add_class::<HttpHeaders>()?;
    m.add_class::<HttpQueryParams>()?;
    m.add_class::<HttpCookies>()?;
    m.add_class::<HttpUrl>()?;
    m.add_class::<HttpTimeout>()?;
    m.add_class::<HttpLimits>()?;
    m.add_class::<HttpBasicAuth>()?;
    m.add_class::<HttpDigestAuth>()?;
    m.add_class::<HttpNetRCAuth>()?;
    
    // Add global functions
    m.add_function(wrap_pyfunction!(global::get, m)?)?;
    m.add_function(wrap_pyfunction!(global::post, m)?)?;
    m.add_function(wrap_pyfunction!(global::put, m)?)?;
    m.add_function(wrap_pyfunction!(global::patch, m)?)?;
    m.add_function(wrap_pyfunction!(global::delete, m)?)?;
    m.add_function(wrap_pyfunction!(global::head, m)?)?;
    m.add_function(wrap_pyfunction!(global::options, m)?)?;
    m.add_function(wrap_pyfunction!(global::request, m)?)?;
    m.add_function(wrap_pyfunction!(global::stream, m)?)?;
    
    // Add exception types
    m.add("HTTPError", py.get_type::<HTTPError>())?;
    m.add("ConnectTimeout", py.get_type::<ConnectTimeout>())?;
    m.add("ReadTimeout", py.get_type::<ReadTimeout>())?;
    m.add("RequestError", py.get_type::<RequestError>())?;
    
    Ok(())
} 