// Allow warnings generated by PyO3 macros
#![allow(non_local_definitions)]

use pyo3::prelude::*;

// Module declarations organized by functionality
mod auth; // Authentication
mod client; // HTTP client implementations
mod config; // Configuration management
mod core; // Core functionality
mod models; // Data models and types
mod optimization; // Performance optimizations
mod stubs;
mod transport; // Transport layer
mod utils; // Utility functions // Placeholder implementations

// Re-export main types and functions - specific imports to avoid shadowing
pub use auth::{AuthType, extract_auth_from_object, extract_auth};
pub use core::{main, error::*, sync_core::SyncHttpClient};
pub use models::{HttpRequest, HttpResponse};
// StreamingHttpResponse and StreamingClient removed - httpx doesn't have these classes
pub use client::{AsyncHttpClient, HttpClient};
pub use config::ClientConfig;
// Re-export API functions (request function is available via Python module, not Rust re-export)
pub use core::api::{delete, get, head, options, patch, post, put, stream};
pub use models::{
    HttpBasicAuth, HttpCookies, HttpCookiesIterator, HttpDigestAuth, HttpHeaders,
    HttpHeadersIterator, HttpLimits, HttpNetRCAuth, HttpQueryParams, HttpTimeout, HttpUrl,
};
pub use utils::EventHooksProxy;

// Python module definition
#[pymodule]
fn _core(py: Python, m: &PyModule) -> PyResult<()> {
    // Initialize Rustls CryptoProvider to avoid runtime panics
    std::sync::Once::new().call_once(|| {
        rustls::crypto::aws_lc_rs::default_provider()
            .install_default()
            .ok();
    });

    // Add classes (httpx-compatible only)
    m.add_class::<HttpRequest>()?;
    m.add_class::<HttpResponse>()?;
    m.add_class::<HttpClient>()?;
    m.add_class::<AsyncHttpClient>()?;
    m.add_class::<SyncHttpClient>()?;

    // Add data model classes
    m.add_class::<HttpHeaders>()?;
    m.add_class::<HttpHeadersIterator>()?;
    m.add_class::<HttpQueryParams>()?;
    m.add_class::<HttpCookies>()?;
    m.add_class::<HttpCookiesIterator>()?;
    m.add_class::<HttpUrl>()?;
    m.add_class::<HttpTimeout>()?;
    m.add_class::<HttpLimits>()?;
    m.add_class::<HttpBasicAuth>()?;
    m.add_class::<HttpDigestAuth>()?;
    m.add_class::<HttpNetRCAuth>()?;

    // Add missing httpx core components
    m.add_class::<models::UseClientDefault>()?;
    m.add_class::<models::BaseTransport>()?;
    m.add_class::<models::AsyncBaseTransport>()?;
    m.add_class::<models::HTTPTransport>()?;
    m.add_class::<models::AsyncHTTPTransport>()?;
    m.add_class::<models::ByteStream>()?;
    m.add_class::<models::SyncByteStream>()?;
    m.add_class::<models::AsyncByteStream>()?;
    m.add_class::<models::ASGITransport>()?;
    m.add_class::<models::WSGITransport>()?;
    m.add_class::<models::Auth>()?;
    m.add_function(wrap_pyfunction!(models::create_ssl_context, m)?)?;

    // Add USE_CLIENT_DEFAULT constant
    m.add("USE_CLIENT_DEFAULT", Py::new(py, models::UseClientDefault)?)?;

    // Add hooks proxy class
    m.add_class::<EventHooksProxy>()?;

    // Transport classes temporarily disabled during hyper migration
    // m.add_class::<transport::FasterhttpTransport>()?;
    m.add_class::<transport::MockTransport>()?;
    // m.add_class::<transport::HTTPSRedirectTransport>()?;

    // Add API functions
    m.add_function(wrap_pyfunction!(core::api::get, m)?)?;
    m.add_function(wrap_pyfunction!(core::api::post, m)?)?;
    m.add_function(wrap_pyfunction!(core::api::put, m)?)?;
    m.add_function(wrap_pyfunction!(core::api::patch, m)?)?;
    m.add_function(wrap_pyfunction!(core::api::delete, m)?)?;
    m.add_function(wrap_pyfunction!(core::api::head, m)?)?;
    m.add_function(wrap_pyfunction!(core::api::options, m)?)?;
    m.add_function(wrap_pyfunction!(core::api::request, m)?)?;
    m.add_function(wrap_pyfunction!(core::api::stream, m)?)?;

    // Add main function for httpx compatibility
    m.add_function(wrap_pyfunction!(core::main, m)?)?;

    // Add batch processing functions for performance
    m.add_function(wrap_pyfunction!(optimization::batch_request, m)?)?;
    m.add_class::<optimization::SmartBatcher>()?;

    // Add zero-copy utilities for performance
    // m.add_class::<zero_copy::ZeroCopyUtils>()?; // Removed - over-engineered

    // Add GIL-free processing for performance
    m.add_function(wrap_pyfunction!(optimization::gil_processed_request, m)?)?; // Updated function name for objective terminology
    m.add_function(wrap_pyfunction!(
        optimization::gil_processed_async_request,
        m
    )?)?; // Updated function name for objective terminology
    m.add_function(wrap_pyfunction!(
        optimization::gil_processed_batch_request,
        m
    )?)?; // Updated function name for objective terminology

    // Exception factory functions - removed new_http_status_error as httpx doesn't have it

    // Add exception types (httpx-compatible only)
    m.add("HTTPError", py.get_type::<HTTPError>())?;

    // Network exceptions
    m.add("NetworkError", py.get_type::<NetworkError>())?;

    // Connection exceptions
    m.add("ConnectError", py.get_type::<ConnectError>())?;
    m.add("ConnectTimeout", py.get_type::<ConnectTimeout>())?;

    // SSL exceptions - removed SSLError as httpx doesn't have it

    // Timeout exceptions
    m.add("TimeoutException", py.get_type::<TimeoutException>())?;
    m.add("ReadTimeout", py.get_type::<ReadTimeout>())?;
    m.add("WriteTimeout", py.get_type::<WriteTimeout>())?;
    m.add("PoolTimeout", py.get_type::<PoolTimeout>())?;

    // Request/Response exceptions
    m.add("RequestError", py.get_type::<RequestError>())?;

    // HTTP Status exceptions
    m.add("HTTPStatusError", py.get_type::<HTTPStatusError>())?;

    // Stream exceptions
    m.add("StreamError", py.get_type::<StreamError>())?;

    // Protocol exceptions
    m.add("ProtocolError", py.get_type::<ProtocolError>())?;
    m.add("TooManyRedirects", py.get_type::<TooManyRedirects>())?;

    // Transport exceptions
    m.add("TransportError", py.get_type::<TransportError>())?;

    // Additional httpx-compatible exceptions
    m.add("InvalidURL", py.get_type::<InvalidURL>())?;
    m.add("LocalProtocolError", py.get_type::<LocalProtocolError>())?;
    m.add("RemoteProtocolError", py.get_type::<RemoteProtocolError>())?;
    m.add("ReadError", py.get_type::<ReadError>())?;
    m.add("WriteError", py.get_type::<WriteError>())?;
    m.add("UnsupportedProtocol", py.get_type::<UnsupportedProtocol>())?;

    // Missing httpx-compatible exceptions
    m.add("NetworkError", py.get_type::<NetworkError>())?;
    m.add("ProxyError", py.get_type::<ProxyError>())?;
    m.add("DecodingError", py.get_type::<DecodingError>())?;
    m.add("CookieConflict", py.get_type::<CookieConflict>())?;
    m.add("CloseError", py.get_type::<CloseError>())?;
    m.add("RequestNotRead", py.get_type::<RequestNotRead>())?;
    m.add("ResponseNotRead", py.get_type::<ResponseNotRead>())?;
    m.add("StreamClosed", py.get_type::<StreamClosed>())?;
    m.add("StreamConsumed", py.get_type::<StreamConsumed>())?;

    Ok(())
}
